import type { Metadata } from "next";
import {  Poppins, Rubik } from "next/font/google";
import "../styles/globals.css";
// import providers

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-poppins",
});
const rubik = Rubik({
  subsets: ["latin"],
  weight: "600",
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${rubik.variable} bg-sec-bg `}>{children}</body>
      {/* modal div */}
    </html>
  );
}
